/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADDIT_H_RPCGEN
#define _ADDIT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct record {
	int first_num;
	int second_num;
};
typedef struct record record;

struct account {
	int ind;
	char user[30];
	char password[30];
};
typedef struct account account;

#define ADDITPROG 0x20000003
#define ADDITVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD_ARGS 1
extern  int * add_args_1(record *, CLIENT *);
extern  int * add_args_1_svc(record *, struct svc_req *);
extern int additprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD_ARGS 1
extern  int * add_args_1();
extern  int * add_args_1_svc();
extern int additprog_1_freeresult ();
#endif /* K&R C */
#define ACCOUNT_MANAGER 2

#if defined(__STDC__) || defined(__cplusplus)
#define AUTENTICATION 1
extern  int * autentication_2(account *, CLIENT *);
extern  int * autentication_2_svc(account *, struct svc_req *);
extern int additprog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define AUTENTICATION 1
extern  int * autentication_2();
extern  int * autentication_2_svc();
extern int additprog_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_record (XDR *, record*);
extern  bool_t xdr_account (XDR *, account*);

#else /* K&R C */
extern bool_t xdr_record ();
extern bool_t xdr_account ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADDIT_H_RPCGEN */
