/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "addit.h"

bool_t
xdr_record (XDR *xdrs, record *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->first_num))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->second_num))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_account (XDR *xdrs, account *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->ind))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->user, 30,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->password, 30,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
