/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADDIT_H_RPCGEN
#define _ADDIT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct record {
	int first_num;
	int second_num;
};
typedef struct record record;

typedef char text_t[30];

typedef char data_t[3000];

typedef int vet[1000];

struct account {
	int ind;
	char login[30];
	char password[30];
};
typedef struct account account;

struct Accounts {
	account user[30];
	int max_users;
};
typedef struct Accounts Accounts;

struct note {
	text_t title;
	text_t user_edit;
	data_t conteudo;
	int num_link;
	int estou_em_uso;
};
typedef struct note note;

struct file {
	text_t title;
	text_t date;
	text_t hour;
	note notes[100];
	int tam_note;
	int permissoes[100];
	int count_permission;
	data_t conteudo_inicial;
	int num_link;
};
typedef struct file file;

#define DOCS 0x20000003
#define DOCUMENTS_MANAGER 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD_ARGS 1
extern  int * add_args_1(record *, CLIENT *);
extern  int * add_args_1_svc(record *, struct svc_req *);
#define NOTAUSO 2
extern  int * notauso_1(int *, CLIENT *);
extern  int * notauso_1_svc(int *, struct svc_req *);
#define ARQEDIT 3
extern  file * arqedit_1(int *, CLIENT *);
extern  file * arqedit_1_svc(int *, struct svc_req *);
#define SAVENOTE 4
extern  int * savenote_1(note *, CLIENT *);
extern  int * savenote_1_svc(note *, struct svc_req *);
#define REQNEWFILE 5
extern  int * reqnewfile_1(account *, CLIENT *);
extern  int * reqnewfile_1_svc(account *, struct svc_req *);
#define CREATENEWFILE 6
extern  int * createnewfile_1(file *, CLIENT *);
extern  int * createnewfile_1_svc(file *, struct svc_req *);
#define SHOWUSERS 7
extern  Accounts * showusers_1(int *, CLIENT *);
extern  Accounts * showusers_1_svc(int *, struct svc_req *);
#define SHOWDOCSPERMISSION 8
extern  int * showdocspermission_1(account *, CLIENT *);
extern  int * showdocspermission_1_svc(account *, struct svc_req *);
extern int docs_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD_ARGS 1
extern  int * add_args_1();
extern  int * add_args_1_svc();
#define NOTAUSO 2
extern  int * notauso_1();
extern  int * notauso_1_svc();
#define ARQEDIT 3
extern  file * arqedit_1();
extern  file * arqedit_1_svc();
#define SAVENOTE 4
extern  int * savenote_1();
extern  int * savenote_1_svc();
#define REQNEWFILE 5
extern  int * reqnewfile_1();
extern  int * reqnewfile_1_svc();
#define CREATENEWFILE 6
extern  int * createnewfile_1();
extern  int * createnewfile_1_svc();
#define SHOWUSERS 7
extern  Accounts * showusers_1();
extern  Accounts * showusers_1_svc();
#define SHOWDOCSPERMISSION 8
extern  int * showdocspermission_1();
extern  int * showdocspermission_1_svc();
extern int docs_1_freeresult ();
#endif /* K&R C */
#define ACCOUNT_MANAGER 2

#if defined(__STDC__) || defined(__cplusplus)
#define AUTHENTICATION 1
extern  int * authentication_2(account *, CLIENT *);
extern  int * authentication_2_svc(account *, struct svc_req *);
extern int docs_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define AUTHENTICATION 1
extern  int * authentication_2();
extern  int * authentication_2_svc();
extern int docs_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_record (XDR *, record*);
extern  bool_t xdr_text_t (XDR *, text_t);
extern  bool_t xdr_data_t (XDR *, data_t);
extern  bool_t xdr_vet (XDR *, vet);
extern  bool_t xdr_account (XDR *, account*);
extern  bool_t xdr_Accounts (XDR *, Accounts*);
extern  bool_t xdr_note (XDR *, note*);
extern  bool_t xdr_file (XDR *, file*);

#else /* K&R C */
extern bool_t xdr_record ();
extern bool_t xdr_text_t ();
extern bool_t xdr_data_t ();
extern bool_t xdr_vet ();
extern bool_t xdr_account ();
extern bool_t xdr_Accounts ();
extern bool_t xdr_note ();
extern bool_t xdr_file ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADDIT_H_RPCGEN */
