/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "addit.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
docs_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		record add_args_1_arg;
		int notauso_1_arg;
		int arqedit_1_arg;
		note savenote_1_arg;
		account reqnewfile_1_arg;
		file createnewfile_1_arg;
		int showusers_1_arg;
		account showdocspermission_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case ADD_ARGS:
		_xdr_argument = (xdrproc_t) xdr_record;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) add_args_1_svc;
		break;

	case NOTAUSO:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) notauso_1_svc;
		break;

	case ARQEDIT:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_file;
		local = (char *(*)(char *, struct svc_req *)) arqedit_1_svc;
		break;

	case SAVENOTE:
		_xdr_argument = (xdrproc_t) xdr_note;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) savenote_1_svc;
		break;

	case REQNEWFILE:
		_xdr_argument = (xdrproc_t) xdr_account;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) reqnewfile_1_svc;
		break;

	case CREATENEWFILE:
		_xdr_argument = (xdrproc_t) xdr_file;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) createnewfile_1_svc;
		break;

	case SHOWUSERS:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_Accounts;
		local = (char *(*)(char *, struct svc_req *)) showusers_1_svc;
		break;

	case SHOWDOCSPERMISSION:
		_xdr_argument = (xdrproc_t) xdr_account;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) showdocspermission_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
docs_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		account authentication_2_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case AUTHENTICATION:
		_xdr_argument = (xdrproc_t) xdr_account;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) authentication_2_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (DOCS, DOCUMENTS_MANAGER);
	pmap_unset (DOCS, ACCOUNT_MANAGER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, DOCS, DOCUMENTS_MANAGER, docs_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (DOCS, DOCUMENTS_MANAGER, udp).");
		exit(1);
	}
	if (!svc_register(transp, DOCS, ACCOUNT_MANAGER, docs_2, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (DOCS, ACCOUNT_MANAGER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, DOCS, DOCUMENTS_MANAGER, docs_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (DOCS, DOCUMENTS_MANAGER, tcp).");
		exit(1);
	}
	if (!svc_register(transp, DOCS, ACCOUNT_MANAGER, docs_2, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (DOCS, ACCOUNT_MANAGER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
